#################################################################################
# Eclipse Tractus-X - Industry Core Hub Frontend
#
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the
# License for the specific language govern in permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
#################################################################################

name: Lint and Test Charts

on:
  push:
    paths:
      - "charts/industry-core-hub/**"
    branches: 
      - main
  pull_request:
    paths:
      - "charts/industry-core-hub/**"
    branches:
      - main
  workflow_dispatch:
    inputs:
      node_image:
        description: "kindest/node image for k8s kind cluster"
        # k8s version from 3.1 release as default
        default: "kindest/node:v1.27.3"
        required: false
        type: string
      upgrade_from:
        description: "chart version to upgrade from"
        default: "0.1.3"
        required: false
        type: string
      helm_version:
        description: "helm version to test (default = latest)"
        default: "latest"
        required: false
        type: string

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Kubernetes KinD Cluster
        uses: container-tools/kind-action@0ad70e2299366b0e1552c7240f4e4567148f723e # v2.0.4
        with:
          # upgrade version, default (v0.17.0) uses node image v1.21.1 and doesn't work with more recent node image versions
          version: v0.27.0
          # default value for event_name != workflow_dispatch
          node_image: ${{ github.event.inputs.node_image || 'kindest/node:v1.27.3' }}

      - name: Set up Helm
        uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4
        with:
          version: ${{ github.event.inputs.helm_version || 'latest' }}

      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: "3.9"
          check-latest: true
      - name: Helm lint
        run: helm lint charts/industry-core-hub -f charts/test-helm-values-ichub.yaml

      - name: Setup Helm repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add bitnami-full-index https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
          helm repo add runix https://helm.runix.net

      - name: Build and load backend image into KinD
        run: |
          docker build -t kind-registry:5000/ichub-backend:ci ./ichub-backend
          kind load docker-image kind-registry:5000/ichub-backend:ci

      - name: Build and load frontend image into KinD
        run: |
          docker build -t kind-registry:5000/ichub-frontend:ci ./ichub-frontend
          kind load docker-image kind-registry:5000/ichub-frontend:ci


      - name: Run chart-testing (install)
        run: |
          helm dependency update charts/industry-core-hub
          helm install test-release charts/industry-core-hub \
            --values charts/test-helm-values-ichub.yaml \
            --set backend.image.repository=kind-registry:5000/ichub-backend \
            --set backend.image.tag=ci \
            --set backend.image.pullPolicy=IfNotPresent \
            --set frontend.image.repository=kind-registry:5000/ichub-frontend \
            --set frontend.image.tag=ci \
            --set frontend.image.pullPolicy=IfNotPresent \
            --timeout 900s \
            --wait

      - name: Helm uninstall
        if: always()
        run: helm uninstall test-release

        # Upgrade the released chart version with the locally available chart
      - name: Run helm upgrade
        run: |
         helm repo add bitnami https://charts.bitnami.com/bitnami
         helm repo add bitnami-full-index https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
         helm repo add runix https://helm.runix.net
         helm repo add tractusx-dev https://eclipse-tractusx.github.io/charts/dev
         helm install industry-core-hub tractusx-dev/industry-core-hub --version ${{ github.event.inputs.upgrade_from || 'x.x.x' }} --values charts/test-helm-values-ichub.yaml --timeout 600s --wait
         helm dependency update charts/industry-core-hub
         helm upgrade industry-core-hub charts/industry-core-hub \
           --values charts/test-helm-values-ichub.yaml \
           --set backend.image.repository=kind-registry:5000/ichub-backend \
           --set backend.image.tag=ci \
           --set backend.image.pullPolicy=IfNotPresent \
           --set frontend.image.repository=kind-registry:5000/ichub-frontend \
           --set frontend.image.tag=ci \
           --set frontend.image.pullPolicy=IfNotPresent \
           --timeout 900s --wait --atomic
        if: github.event_name != 'pull_request'
